const primitive = {
  static: {
    black: "#000000",
    white: "#FFFFFF",
  },
  brand: {
    mist: "#A1C6F2",
    sky: "#56B2ED",
  },
  gray: {
    1: "#FCFCFB",
    2: "#F7F7F5",
    3: "#EFEEED",
    4: "#E4E5E4",
    5: "#D9DEDF",
    6: "#C7CED0",
    7: "#B0BCC0",
    8: "#87979D",
    9: "#7B898F",
    10: "#65747C",
    11: "#405866",
    12: "#021826",
  },
  blue: {
    1: "#F4F8FC",
    2: "#EAF1F8",
    3: "#DCE8F3",
    4: "#CBDBEA",
    5: "#B6CCE0",
    6: "#9CBAD3",
    7: "#7EA5C2",
    8: "#5D8CAB",
    9: "#3E6F92",
    10: "#224E82",
    11: "#17395F",
    12: "#102944",
  },
  info: {
    1: "#FAFBFF",
    2: "#F5F7FF",
    3: "#EBEFFF",
    4: "#E0E7FF",
    5: "#CFDAFF",
    6: "#BBCAFF",
    7: "#A8BCFF",
    8: "#8DA9FF",
    9: "#4F7FFF",
    10: "#366CFE",
    11: "#2962FD",
    12: "#082BA3",
  },
  green: {
    1: "#F2FBF5",
    2: "#E5F6EB",
    3: "#D4EFDE",
    4: "#BDE3CB",
    5: "#9FD5B4",
    6: "#7BC395",
    7: "#55AD76",
    8: "#358C5A",
    9: "#217848",
    10: "#176B3A",
    11: "#10512A",
    12: "#082D18",
  },
  amber: {
    1: "#FFFBF0",
    2: "#FFF4D6",
    3: "#FFE9B3",
    4: "#FFD98A",
    5: "#F7C965",
    6: "#E8B24A",
    7: "#D5962E",
    8: "#B97914",
    9: "#9B6B08",
    10: "#875B00",
    11: "#624300",
    12: "#3A2700",
  },
  red: {
    1: "#FFF5F4",
    2: "#FEEAE8",
    3: "#FBD9D6",
    4: "#F6C1BC",
    5: "#E9A39D",
    6: "#D9837B",
    7: "#C7655D",
    8: "#B24A43",
    9: "#A63732",
    10: "#9A2626",
    11: "#721A1A",
    12: "#421010",
  },
} as const;

const focus = {
  outline: primitive.blue[10],
  ring: "rgb(34 78 130 / 28%)",
} as const;

const border = {
  width: {
    none: "0px",
    thin: "1px",
    thick: "2px",
  },
  style: {
    none: "none",
    solid: "solid",
    dashed: "dashed",
  },
} as const;

const space = {
  0: "0rem",
  "0_5": "0.125rem",
  1: "0.25rem",
  2: "0.5rem",
  3: "0.75rem",
  4: "1rem",
  5: "1.25rem",
  6: "1.5rem",
  8: "2rem",
  10: "2.5rem",
  12: "3rem",
  16: "4rem",
  20: "5rem",
  24: "6rem",
} as const;

const foundation = {
  color: {
    primitive,
    surface: {
      canvas: primitive.gray[1],
      chrome: primitive.blue[1],
      raised: primitive.static.white,
      subtle: primitive.gray[2],
      sunken: primitive.gray[3],
      inverse: primitive.gray[12],
      brand: primitive.gray[12],
      brandRail: primitive.brand.mist,
      brandSubtle: primitive.blue[12],
      brandTranslucent: "rgb(2 24 38 / 64%)",
      brandGlass: "rgb(255 255 255 / 10%)",
      brandGlassHover: "rgb(255 255 255 / 16%)",
      brandGlassActive: "rgb(255 255 255 / 20%)",
    },
    accent: {
      default: primitive.gray[12],
      hover: primitive.blue[12],
      active: primitive.blue[11],
      secondary: primitive.brand.sky,
      secondaryHover: primitive.blue[7],
      secondaryActive: primitive.blue[8],
    },
    text: {
      primary: primitive.gray[12],
      secondary: primitive.gray[11],
      muted: primitive.gray[10],
      inverse: primitive.static.white,
      onBrand: primitive.static.white,
      onBrandMuted: primitive.blue[4],
    },
    action: {
      primary: primitive.blue[10],
      primaryHover: primitive.blue[11],
      primaryActive: primitive.blue[12],
      primarySubtle: primitive.blue[1],
      primarySubtleHover: primitive.blue[2],
      secondary: primitive.blue[2],
      secondaryHover: primitive.blue[3],
    },
    focus,
    border: {
      subtle: primitive.gray[5],
      default: primitive.gray[6],
      strong: primitive.gray[8],
      focus: focus.outline,
      brandSurface: "rgb(93 140 171 / 34%)",
      onBrand: "rgb(255 255 255 / 24%)",
    },
    status: {
      neutral: primitive.gray[11],
      neutralStrong: primitive.gray[12],
      neutralSubtle: primitive.gray[1],
      neutralSurface: primitive.gray[3],
      neutralHover: primitive.gray[4],
      neutralActive: primitive.gray[5],
      neutralBorder: primitive.gray[5],
      success: primitive.green[10],
      successStrong: primitive.green[12],
      successSubtle: primitive.green[1],
      successSurface: primitive.green[3],
      successHover: primitive.green[4],
      successActive: primitive.green[5],
      successBorder: primitive.green[5],
      warning: primitive.amber[10],
      warningStrong: primitive.amber[12],
      warningSubtle: primitive.amber[1],
      warningSurface: primitive.amber[3],
      warningHover: primitive.amber[4],
      warningActive: primitive.amber[5],
      warningBorder: primitive.amber[5],
      danger: primitive.red[10],
      dangerStrong: primitive.red[12],
      dangerSubtle: primitive.red[1],
      dangerSurface: primitive.red[3],
      dangerHover: primitive.red[4],
      dangerActive: primitive.red[5],
      dangerBorder: primitive.red[5],
      info: primitive.info[11],
      infoStrong: primitive.info[12],
      infoSubtle: primitive.info[1],
      infoSurface: primitive.info[3],
      infoHover: primitive.info[4],
      infoActive: primitive.info[5],
      infoBorder: primitive.info[6],
    },
  },
  font: {
    family: {
      sans: '"Sora Variable", Sora, Arial, "Helvetica Neue", sans-serif',
      mono: '"SFMono-Regular", Consolas, "Liberation Mono", monospace',
    },
    weight: {
      light: 300,
      regular: 400,
      medium: 500,
      semibold: 600,
    },
    size: {
      "2xs": "0.625rem",
      xs: "0.75rem",
      sm: "0.875rem",
      md: "1rem",
      lg: "1.125rem",
      xl: "1.5rem",
      "2xl": "2rem",
    },
    lineHeight: {
      tight: 1.2,
      default: 1.5,
      relaxed: 1.6,
    },
    letterSpacing: {
      normal: "0em",
      wide: "0.05em",
    },
    variantNumeric: {
      tabular: "tabular-nums",
    },
  },
  space,
  radius: {
    none: "0rem",
    xs: "0.25rem",
    sm: "0.5rem",
    md: "0.75rem",
    lg: "1rem",
    xl: "1.5rem",
    pill: "999px",
  },
  shape: {
    none: "0rem",
    control: "0.75rem",
    surface: "1rem",
    overlay: "1rem",
    pill: "999px",
  },
  layer: {
    modal: 50,
  },
  border,
  focus: {
    width: border.width.thick,
    style: border.style.solid,
    offset: space["0_5"],
  },
  elevation: {
    flat: "none",
    raised: "0 1px 2px rgb(2 24 38 / 6%), 0 1px 1px rgb(2 24 38 / 4%)",
    lifted: "0 4px 12px rgb(2 24 38 / 8%)",
    floating: "0 8px 24px rgb(2 24 38 / 10%)",
    interactive: "0 16.64px 49.92px 0 rgb(34 78 130 / 10%), 0 4.16px 12.48px 0 rgb(7 88 140 / 10%)",
    overlay: "0 16px 40px rgb(2 24 38 / 14%)",
  },
  effect: {
    blur: {
      brandMedia: "2rem",
      brandSurface: "0.125rem",
      floatingSurface: "1rem",
      glassControl: "0.25rem",
      // Compatibilidade: use brandMedia em novos consumidores.
      brand: "2rem",
    },
    glow: {
      brand: "0 24px 80px rgb(93 140 171 / 28%)",
    },
    highlight: {
      brand: "inset 0 1px 0 rgb(255 255 255 / 18%)",
      brandSurface: "inset 0 1px 0 rgb(126 165 194 / 58%)",
      glassControl: "inset 0 1px 0 rgb(255 255 255 / 80%), inset 0 -1px 0 rgb(255 255 255 / 20%)",
    },
    // Compatibilidade: aliases do contrato preliminar de vidro.
    glass: {
      backdropBlur: "0.25rem",
      shadow: "inset 0 1px 0 rgb(255 255 255 / 80%), inset 0 -1px 0 rgb(255 255 255 / 20%)",
    },
  },
  gradient: {
    surface: {
      action: `linear-gradient(141deg, ${primitive.blue[9]} 0%, ${primitive.gray[12]} 100%)`,
      brand:
        "radial-gradient(85% 60% at 50% 0%, rgb(93 140 171 / 34%) 0%, transparent 72%), linear-gradient(rgb(2 24 38 / 64%) 0 100%)",
    },
    text: {
      onDark: `linear-gradient(90deg, ${primitive.static.white} 29.789%, #309BDE 100%)`,
      onLight: `linear-gradient(90deg, ${primitive.blue[9]} 0%, ${primitive.gray[12]} 100%)`,
    },
  },
  control: {
    height: {
      sm: "2.25rem",
      md: "2.75rem",
      lg: "3.125rem",
    },
    focusRing: `0 0 0 3px ${focus.ring}`,
  },
  motion: {
    cycle: {
      ambient: "1600ms",
      loading: "800ms",
      skeleton: "1800ms",
    },
    duration: {
      ambient: "1600ms",
      enter: "240ms",
      fast: "120ms",
      instant: "0ms",
      moderate: "180ms",
      normal: "180ms",
      slow: "240ms",
    },
    easing: "cubic-bezier(0.2, 0, 0, 1)",
    easings: {
      accelerate: "cubic-bezier(0.4, 0, 1, 1)",
      decelerate: "cubic-bezier(0, 0, 0.2, 1)",
      linear: "linear",
      standard: "cubic-bezier(0.2, 0, 0, 1)",
    },
    role: {
      enter: {
        duration: "240ms",
        easing: "cubic-bezier(0, 0, 0.2, 1)",
      },
      exit: {
        duration: "180ms",
        easing: "cubic-bezier(0.4, 0, 1, 1)",
      },
      feedback: {
        duration: "120ms",
        easing: "cubic-bezier(0.2, 0, 0, 1)",
      },
      progress: {
        duration: "240ms",
        easing: "cubic-bezier(0.2, 0, 0, 1)",
      },
      state: {
        duration: "180ms",
        easing: "cubic-bezier(0.2, 0, 0, 1)",
      },
    },
  },
} as const;

const spacing = {
  default: {
    flow: {
      stack: {
        "2xs": foundation.space[1],
        xs: foundation.space[2],
        sm: foundation.space[3],
        md: foundation.space[4],
        lg: foundation.space[6],
        xl: foundation.space[8],
      },
      inline: {
        "2xs": foundation.space[1],
        xs: foundation.space[2],
        sm: foundation.space[3],
        md: foundation.space[4],
        lg: foundation.space[6],
      },
    },
    inset: {
      "2xs": foundation.space[1],
      xs: foundation.space[2],
      sm: foundation.space[3],
      md: foundation.space[4],
      lg: foundation.space[6],
    },
    grid: {
      sm: foundation.space[2],
      md: foundation.space[4],
      lg: foundation.space[6],
    },
  },
  compact: {
    flow: {
      stack: {
        "2xs": foundation.space[1],
        xs: foundation.space[1],
        sm: foundation.space[2],
        md: foundation.space[3],
        lg: foundation.space[4],
        xl: foundation.space[6],
      },
      inline: {
        "2xs": foundation.space[1],
        xs: foundation.space[1],
        sm: foundation.space[2],
        md: foundation.space[3],
        lg: foundation.space[4],
      },
    },
    inset: {
      "2xs": foundation.space[1],
      xs: foundation.space[1],
      sm: foundation.space[2],
      md: foundation.space[3],
      lg: foundation.space[4],
    },
    grid: {
      sm: foundation.space[2],
      md: foundation.space[3],
      lg: foundation.space[4],
    },
  },
  section: {
    sm: foundation.space[8],
    md: foundation.space[12],
    lg: foundation.space[16],
    xl: foundation.space[20],
  },
  gutter: {
    sm: foundation.space[4],
    md: foundation.space[6],
    lg: foundation.space[8],
  },
} as const;

const layout = {
  breakpoint: {
    regular: "40rem",
    expanded: "48rem",
    wide: "64rem",
  },
  grid: {
    columns: {
      compact: 4,
      regular: 8,
      wide: 12,
    },
    gap: {
      compact: spacing.default.grid.md,
      regular: spacing.default.grid.lg,
      wide: spacing.default.grid.lg,
    },
  },
  gutter: {
    compact: spacing.gutter.sm,
    regular: spacing.gutter.md,
    wide: spacing.gutter.lg,
  },
  container: {
    focused: "40rem",
    reading: "48rem",
    standard: "72rem",
    wide: "92rem",
  },
} as const;

const typography = {
  heading: {
    page: {
      fontFamily: foundation.font.family.sans,
      fontSize: {
        compact: foundation.font.size.xl,
        wide: foundation.font.size["2xl"],
      },
      fontWeight: foundation.font.weight.medium,
      letterSpacing: foundation.font.letterSpacing.normal,
      lineHeight: foundation.font.lineHeight.tight,
    },
    section: {
      fontFamily: foundation.font.family.sans,
      fontSize: foundation.font.size.xl,
      fontWeight: foundation.font.weight.medium,
      letterSpacing: foundation.font.letterSpacing.normal,
      lineHeight: foundation.font.lineHeight.tight,
    },
    component: {
      fontFamily: foundation.font.family.sans,
      fontSize: foundation.font.size.lg,
      fontWeight: foundation.font.weight.medium,
      letterSpacing: foundation.font.letterSpacing.normal,
      lineHeight: foundation.font.lineHeight.tight,
    },
  },
  body: {
    default: {
      fontFamily: foundation.font.family.sans,
      fontSize: foundation.font.size.md,
      fontWeight: foundation.font.weight.regular,
      letterSpacing: foundation.font.letterSpacing.normal,
      lineHeight: foundation.font.lineHeight.default,
    },
    supporting: {
      fontFamily: foundation.font.family.sans,
      fontSize: foundation.font.size.sm,
      fontWeight: foundation.font.weight.regular,
      letterSpacing: foundation.font.letterSpacing.normal,
      lineHeight: foundation.font.lineHeight.default,
    },
    long: {
      fontFamily: foundation.font.family.sans,
      fontSize: foundation.font.size.md,
      fontWeight: foundation.font.weight.regular,
      letterSpacing: foundation.font.letterSpacing.normal,
      lineHeight: foundation.font.lineHeight.relaxed,
    },
  },
  label: {
    default: {
      fontFamily: foundation.font.family.sans,
      fontSize: foundation.font.size.sm,
      fontWeight: foundation.font.weight.medium,
      letterSpacing: foundation.font.letterSpacing.normal,
      lineHeight: foundation.font.lineHeight.default,
    },
    compact: {
      fontFamily: foundation.font.family.sans,
      fontSize: foundation.font.size.xs,
      fontWeight: foundation.font.weight.medium,
      letterSpacing: foundation.font.letterSpacing.normal,
      lineHeight: foundation.font.lineHeight.default,
    },
  },
  caption: {
    fontFamily: foundation.font.family.sans,
    fontSize: foundation.font.size.xs,
    fontWeight: foundation.font.weight.regular,
    letterSpacing: foundation.font.letterSpacing.normal,
    lineHeight: foundation.font.lineHeight.default,
  },
  data: {
    fontFamily: foundation.font.family.sans,
    fontSize: foundation.font.size.sm,
    fontVariantNumeric: foundation.font.variantNumeric.tabular,
    fontWeight: foundation.font.weight.medium,
    letterSpacing: foundation.font.letterSpacing.normal,
    lineHeight: foundation.font.lineHeight.default,
  },
  code: {
    fontFamily: foundation.font.family.mono,
    fontSize: foundation.font.size.sm,
    fontWeight: foundation.font.weight.regular,
    letterSpacing: foundation.font.letterSpacing.normal,
    lineHeight: foundation.font.lineHeight.default,
  },
} as const;

export const tokens = {
  ...foundation,
  layout,
  spacing,
  typography,
  component: {
    button: {
      disabled: {
        background: foundation.color.surface.sunken,
        border: foundation.color.border.subtle,
        text: foundation.color.text.muted,
      },
      focusRing: `0 0 0 4px ${foundation.color.focus.ring}`,
      fontWeight: typography.label.default.fontWeight,
      gap: foundation.space[1],
      minHeight: "3.25rem",
      padding: {
        block: foundation.space[3],
        inline: foundation.space[8],
      },
      paddingBlock: foundation.space[3],
      paddingInline: foundation.space[8],
      radius: foundation.radius.pill,
      shadow: foundation.elevation.raised,
      size: {
        xs: {
          fontSize: typography.caption.fontSize,
          iconSize: foundation.space[4],
          lineHeight: foundation.space[4],
          minHeight: "2.25rem",
          paddingBlock: foundation.space[1],
          paddingInline: foundation.space[3],
          paddingInlineEndWithTrailingIcon: foundation.space[2],
          radius: foundation.radius.pill,
        },
        lg: {
          fontSize: typography.body.default.fontSize,
          iconSize: foundation.space[6],
          minHeight: "3.75rem",
          paddingBlock: foundation.space[4],
          paddingInline: foundation.space[10],
          paddingInlineEndWithTrailingIcon: foundation.space[8],
          radius: foundation.radius.pill,
        },
        md: {
          fontSize: typography.label.default.fontSize,
          iconSize: foundation.space[6],
          minHeight: "3.25rem",
          paddingBlock: foundation.space[3],
          paddingInline: foundation.space[8],
          paddingInlineEndWithTrailingIcon: foundation.space[6],
          radius: foundation.radius.pill,
        },
        sm: {
          fontSize: typography.label.default.fontSize,
          iconSize: foundation.space[5],
          lineHeight: foundation.space[5],
          minHeight: "2.75rem",
          paddingBlock: foundation.space[2],
          paddingInline: foundation.space[6],
          paddingInlineEndWithTrailingIcon: foundation.space[4],
          radius: foundation.radius.pill,
        },
      },
      primary: {
        background: foundation.color.action.primary,
        backgroundActive: foundation.color.accent.default,
        backgroundHover: foundation.color.accent.hover,
        text: foundation.color.text.inverse,
        textActive: foundation.color.text.inverse,
        textHover: foundation.color.text.onBrandMuted,
      },
      secondary: {
        background: foundation.color.surface.subtle,
        backgroundActive: foundation.color.surface.sunken,
        backgroundHover: foundation.color.action.primarySubtle,
        border: foundation.color.border.subtle,
        text: foundation.color.text.primary,
      },
      tertiary: {
        background: foundation.color.action.secondary,
        backgroundActive: foundation.color.action.secondaryHover,
        backgroundHover: foundation.color.action.secondaryHover,
        text: foundation.color.text.primary,
      },
      outline: {
        background: "transparent",
        backgroundActive: foundation.color.surface.sunken,
        backgroundHover: foundation.color.action.primarySubtle,
        border: foundation.color.border.default,
        borderHover: foundation.color.action.primary,
        text: foundation.color.text.primary,
      },
      surface: {
        background: foundation.color.surface.subtle,
        backgroundActive: foundation.color.surface.sunken,
        backgroundHover: foundation.color.action.primarySubtle,
        border: foundation.color.border.subtle,
        text: foundation.color.text.secondary,
      },
      ghost: {
        border: foundation.color.border.subtle,
        text: foundation.color.text.primary,
      },
      danger: {
        background: foundation.color.status.danger,
        backgroundActive: foundation.color.status.dangerStrong,
        backgroundHover: foundation.color.status.dangerStrong,
        text: foundation.color.text.inverse,
      },
      dangerSoft: {
        background: foundation.color.status.dangerSurface,
        backgroundActive: foundation.color.status.dangerActive,
        backgroundHover: foundation.color.status.dangerHover,
        border: foundation.color.status.dangerBorder,
        text: foundation.color.status.danger,
      },
      gradient: {
        background: foundation.gradient.surface.action,
        backgroundActive: `linear-gradient(rgb(2 24 38 / 12%), rgb(2 24 38 / 12%)), ${foundation.gradient.surface.action}`,
        backgroundHover: `linear-gradient(rgb(255 255 255 / 10%), rgb(255 255 255 / 10%)), ${foundation.gradient.surface.action}`,
        shadow: `${foundation.effect.highlight.brand}, inset 0 6px 12px rgb(255 255 255 / 8%), ${foundation.elevation.raised}`,
        text: foundation.color.text.inverse,
      },
      glass: {
        backdropBlur: foundation.effect.blur.glassControl,
        background: foundation.color.action.secondary,
        backgroundActive: foundation.color.action.secondaryHover,
        backgroundHover: foundation.color.action.primarySubtle,
        border: foundation.color.border.brandSurface,
        radius: foundation.radius.pill,
        shadow: foundation.effect.highlight.glassControl,
        text: foundation.color.text.primary,
        textDisabled: foundation.color.text.muted,
      },
      adaptiveGlass: {
        backdropBlur: "1rem",
        background: "rgb(244 248 252 / 16%)",
        backgroundActive: "rgb(244 248 252 / 28%)",
        backgroundHover: "rgb(244 248 252 / 22%)",
        border: "rgb(255 255 255 / 64%)",
        highlight: "inset 0 1px 0 rgb(255 255 255 / 88%), inset 0 -1px 0 rgb(34 78 130 / 8%)",
        onDark: {
          border: "rgb(161 198 242 / 56%)",
          highlight: "inset 0 1px 0 rgb(211 232 255 / 72%), inset 0 -1px 0 rgb(86 178 237 / 22%)",
          outline: "rgb(86 178 237 / 18%)",
          sheen:
            "linear-gradient(135deg, rgb(211 232 255 / 12%) 0%, rgb(255 255 255 / 2%) 46%, rgb(86 178 237 / 10%) 100%)",
          text: foundation.color.text.inverse,
        },
        outline: "rgb(34 78 130 / 8%)",
        shadow: "none",
        sheen:
          "linear-gradient(135deg, rgb(255 255 255 / 18%) 0%, rgb(255 255 255 / 2%) 50%, rgb(161 198 242 / 3%) 100%)",
        text: foundation.color.text.primary,
      },
    },
    checkbox: {
      control: {
        background: foundation.color.surface.subtle,
        backgroundChecked: foundation.color.accent.secondary,
        backgroundCheckedHover: foundation.color.accent.secondaryHover,
        backgroundDisabled: foundation.color.surface.subtle,
        backgroundDisabledChecked: foundation.color.action.secondary,
        backgroundHover: foundation.color.surface.subtle,
        border: foundation.color.border.subtle,
        borderDisabled: foundation.color.border.subtle,
        borderError: foundation.color.status.danger,
        borderFocus: foundation.color.border.focus,
        borderHover: foundation.color.border.subtle,
        focusRing: `0 0 0 4px ${foundation.color.focus.ring}, 0 1px 2px rgb(2 24 38 / 4%)`,
        mark: foundation.color.text.primary,
        markDisabled: foundation.color.text.inverse,
        radius: foundation.radius.xs,
        shadow: foundation.elevation.raised,
      },
      size: {
        lg: "1.25rem",
        md: "1rem",
      },
    },
    field: {
      control: {
        background: foundation.color.surface.raised,
        border: foundation.color.border.strong,
        borderError: foundation.color.status.danger,
        fontSize: typography.body.supporting.fontSize,
        icon: foundation.color.action.primary,
        text: foundation.color.text.primary,
      },
      error: foundation.color.status.danger,
      help: foundation.color.text.secondary,
      label: foundation.color.text.primary,
      labelFontWeight: typography.label.default.fontWeight,
    },
    radio: {
      control: {
        background: foundation.color.surface.raised,
        backgroundDisabled: foundation.color.surface.subtle,
        border: foundation.color.border.strong,
        borderChecked: foundation.color.accent.secondary,
        borderDisabled: foundation.color.border.subtle,
        borderError: foundation.color.status.danger,
        borderFocus: foundation.color.border.focus,
        borderHover: foundation.color.action.primary,
        dot: foundation.color.accent.secondary,
        dotDisabled: foundation.color.text.muted,
        focusRing: foundation.control.focusRing,
        size: foundation.space[5],
      },
    },
    logo: {
      color: {
        inverse: foundation.color.text.inverse,
        primary: foundation.color.accent.default,
        secondary: foundation.color.action.primary,
        support: foundation.color.surface.sunken,
      },
    },
    textarea: {
      background: foundation.color.surface.raised,
      backgroundDisabled: foundation.color.surface.subtle,
      backgroundError: foundation.color.status.dangerSubtle,
      border: foundation.color.border.default,
      borderDisabled: foundation.color.border.subtle,
      borderError: foundation.color.status.danger,
      borderFocus: foundation.color.border.focus,
      borderHover: foundation.color.action.secondaryHover,
      counterText: foundation.color.text.muted,
      focusRing: `0 0 0 3px ${foundation.color.focus.ring}, 0 1px 2px rgb(2 24 38 / 4%)`,
      fontSize: typography.body.supporting.fontSize,
      fontWeight: typography.body.supporting.fontWeight,
      minHeight: "7.5rem",
      placeholder: foundation.color.text.muted,
      radius: foundation.shape.control,
      shadow: foundation.elevation.raised,
      text: foundation.color.text.primary,
      textDisabled: foundation.color.text.muted,
      textError: foundation.color.status.danger,
    },
    select: {
      popover: {
        shadow: foundation.elevation.floating,
      },
    },
    sidebar: {
      collapsedBrandSize: "1.75rem",
      collapsedWidth: "4.5rem",
      headerHeight: "3.75rem",
      width: "17.5rem",
    },
    progress: {
      indicator: foundation.color.accent.secondary,
      meta: foundation.color.text.secondary,
      track: foundation.color.action.secondary,
    },
    spinner: {
      color: {
        danger: foundation.color.status.danger,
        info: foundation.color.status.info,
        inverse: foundation.color.text.inverse,
        neutral: foundation.color.text.secondary,
        primary: foundation.color.action.primary,
        secondary: foundation.color.accent.secondary,
        success: foundation.color.status.success,
        warning: foundation.color.status.warning,
      },
      size: {
        xs: foundation.space[3],
        sm: foundation.space[4],
        md: foundation.space[5],
        lg: foundation.space[8],
        xl: foundation.space[10],
      },
    },
    pageHeader: {
      action: {
        background: foundation.color.surface.raised,
        border: foundation.color.border.subtle,
      },
      backdropBlur: "0px",
      background: foundation.color.surface.raised,
      border: foundation.color.border.subtle,
      eyebrow: {
        background: foundation.color.action.secondary,
        text: foundation.color.action.primary,
      },
      radius: foundation.shape.surface,
      shadow: foundation.elevation.flat,
    },
    saveStatus: {
      radar: {
        duration: foundation.motion.cycle.ambient,
        opacity: 0.4,
        scale: 3,
      },
    },
    stepCard: {
      indicatorRadius: foundation.shape.surface,
      interactiveShadow: foundation.elevation.raised,
      radius: foundation.shape.surface,
    },
    stickyActionBar: {
      backdropBlur: foundation.effect.blur.floatingSurface,
      background: "rgb(244 248 252 / 16%)",
      border: "rgb(255 255 255 / 64%)",
      highlight: "inset 0 1px 0 rgb(255 255 255 / 88%), inset 0 -1px 0 rgb(34 78 130 / 8%)",
      outline: "rgb(34 78 130 / 8%)",
      onDark: {
        disabled: {
          background: foundation.color.surface.brandGlassHover,
          border: foundation.color.border.onBrand,
          text: foundation.color.text.onBrandMuted,
        },
        primary: {
          background: foundation.color.surface.raised,
          backgroundActive: foundation.color.action.secondaryHover,
          backgroundHover: foundation.color.action.secondary,
          text: foundation.color.text.primary,
        },
        surface: {
          border: "rgb(161 198 242 / 56%)",
          highlight: "inset 0 1px 0 rgb(211 232 255 / 72%), inset 0 -1px 0 rgb(86 178 237 / 22%)",
          outline: "rgb(86 178 237 / 18%)",
          sheen:
            "linear-gradient(135deg, rgb(211 232 255 / 12%) 0%, rgb(255 255 255 / 2%) 46%, rgb(86 178 237 / 10%) 100%)",
        },
        secondary: {
          background: foundation.color.surface.brandGlass,
          backgroundActive: foundation.color.surface.brandGlassActive,
          backgroundHover: foundation.color.surface.brandGlassHover,
          border: "rgb(255 255 255 / 56%)",
          text: foundation.color.text.inverse,
        },
        status: {
          error: foundation.color.status.dangerHover,
          saved: foundation.color.status.successHover,
          text: foundation.color.text.inverse,
        },
      },
      radius: foundation.shape.surface,
      sheen:
        "linear-gradient(135deg, rgb(255 255 255 / 18%) 0%, rgb(255 255 255 / 2%) 50%, rgb(161 198 242 / 3%) 100%)",
      shadow: foundation.elevation.floating,
    },
    slider: {
      accent: foundation.color.accent.secondary,
      accentError: foundation.color.status.danger,
      thumb: {
        background: foundation.color.action.primary,
        backgroundHover: foundation.color.action.primaryHover,
        border: "rgb(255 255 255 / 42%)",
        shadow:
          "0 2px 5px rgb(2 24 38 / 20%), inset 0 1px 0 rgb(255 255 255 / 28%), inset 0 -1px 0 rgb(2 24 38 / 16%)",
      },
      track: {
        background: foundation.color.surface.sunken,
      },
      value: {
        text: foundation.color.text.primary,
      },
    },
    tabs: {
      indicator: {
        background: foundation.color.surface.raised,
        secondaryBackground: foundation.color.accent.secondary,
        shadow: foundation.elevation.raised,
        thickness: "2px",
      },
      list: {
        background: foundation.color.surface.sunken,
        border: foundation.color.border.subtle,
        radius: foundation.space[5],
        trackThickness: border.width.thin,
      },
      panel: {
        text: foundation.color.text.primary,
      },
      radius: foundation.shape.pill,
      tab: {
        backgroundHover: foundation.color.surface.subtle,
        compactHeight: foundation.space[6],
        height: foundation.space[8],
        radius: foundation.shape.pill,
        text: foundation.color.text.secondary,
        textSelected: foundation.color.text.primary,
      },
    },
    table: {
      background: foundation.color.surface.raised,
      border: foundation.color.border.subtle,
      cell: {
        text: foundation.color.text.primary,
      },
      footer: {
        background: foundation.color.surface.subtle,
      },
      header: {
        background: foundation.color.surface.subtle,
        text: foundation.color.text.secondary,
      },
      minWidth: "40rem",
      radius: foundation.shape.surface,
      row: {
        background: foundation.color.surface.raised,
        backgroundHover: foundation.color.action.primarySubtle,
        backgroundSelected: foundation.color.action.secondary,
      },
    },
    tooltip: {
      background: foundation.color.surface.inverse,
      fontSize: typography.label.default.fontSize,
      fontWeight: typography.label.default.fontWeight,
      maxWidth: "16rem",
      paddingBlock: spacing.default.inset.xs,
      paddingInline: spacing.default.inset.sm,
      radius: foundation.shape.overlay,
      shadow: foundation.elevation.floating,
      text: foundation.color.text.inverse,
    },
    alert: {
      featured: {
        auraBlockSize: "32rem",
        auraBlur: foundation.effect.blur.brandMedia,
        auraInlineSize: "32rem",
        auraOpacity: 0.56,
        background: foundation.color.surface.raised,
        border: foundation.color.status.neutralSurface,
        close: {
          background: foundation.color.surface.raised,
          border: foundation.color.border.default,
        },
        contentGap: spacing.default.flow.stack.md,
        contentPaddingBlock: spacing.default.inset.lg,
        contentPaddingInline: spacing.default.inset.lg,
        divider: foundation.color.border.subtle,
        footerGap: spacing.default.flow.inline.sm,
        footerPaddingBlock: spacing.default.inset.md,
        footerPaddingInline: spacing.default.inset.lg,
        iconContainerSize: foundation.control.height.md,
        shadow: foundation.elevation.lifted,
      },
      gap: spacing.default.flow.inline.sm,
      iconSize: foundation.space[5],
      paddingBlock: spacing.default.inset.sm,
      paddingInline: spacing.default.inset.md,
      radius: foundation.shape.surface,
      shadow: foundation.elevation.raised,
      danger: {
        aura: foundation.color.status.dangerSurface,
        background: foundation.color.status.dangerSubtle,
        border: foundation.color.status.dangerBorder,
        icon: {
          background: foundation.color.status.danger,
          border: foundation.color.status.danger,
          text: foundation.color.text.inverse,
        },
        text: foundation.color.status.danger,
      },
      info: {
        aura: foundation.color.status.infoSurface,
        background: foundation.color.status.infoSubtle,
        border: foundation.color.status.infoBorder,
        icon: {
          background: foundation.color.status.info,
          border: foundation.color.status.info,
          text: foundation.color.text.inverse,
        },
        text: foundation.color.status.infoStrong,
      },
      success: {
        aura: foundation.color.status.successSurface,
        background: foundation.color.status.successSubtle,
        border: foundation.color.status.successBorder,
        icon: {
          background: foundation.color.status.success,
          border: foundation.color.status.success,
          text: foundation.color.text.inverse,
        },
        text: foundation.color.status.success,
      },
      warning: {
        aura: foundation.color.status.warningSurface,
        background: foundation.color.status.warningSubtle,
        border: foundation.color.status.warningBorder,
        icon: {
          background: foundation.color.status.warningSurface,
          border: foundation.color.status.warningBorder,
          text: foundation.color.status.warning,
        },
        text: foundation.color.status.warning,
      },
    },
    overlay: {
      backdrop: "rgb(12 18 28 / 56%)",
      background: foundation.color.surface.raised,
      border: foundation.color.border.subtle,
      radius: foundation.shape.overlay,
      shadow: foundation.elevation.overlay,
      zIndex: foundation.layer.modal,
    },
    statusBadge: {
      checkMark: foundation.color.text.inverse,
      fontWeight: typography.label.default.fontWeight,
      gap: spacing.default.flow.inline["2xs"],
      radius: foundation.shape.pill,
      solidFontWeight: foundation.font.weight.regular,
      size: {
        xs: {
          fontSize: typography.caption.fontSize,
          iconSize: "0.75rem",
          lineHeight: "0.875rem",
          minHeight: "1.25rem",
          paddingBlock: foundation.space["0_5"],
          paddingInline: spacing.default.inset["2xs"],
          paddingInlineStartWithLeadingIcon: foundation.space["0_5"],
          paddingInlineWithIcon: foundation.space["0_5"],
        },
        md: {
          fontSize: typography.label.default.fontSize,
          iconSize: foundation.space[5],
          lineHeight: foundation.space[5],
          minHeight: "1.75rem",
          paddingBlock: spacing.default.inset["2xs"],
          paddingInline: spacing.default.inset.sm,
          paddingInlineStartWithLeadingIcon: spacing.default.inset.xs,
          paddingInlineWithIcon: spacing.default.inset.sm,
        },
        sm: {
          fontSize: typography.caption.fontSize,
          iconSize: foundation.space[4],
          lineHeight: "1.125rem",
          minHeight: "1.5rem",
          paddingBlock: foundation.space["0_5"],
          paddingInline: spacing.default.inset.xs,
          paddingInlineStartWithLeadingIcon: spacing.default.inset.xs,
          paddingInlineWithIcon: spacing.default.inset.sm,
        },
      },
      neutral: {
        background: foundation.color.status.neutralSubtle,
        border: foundation.color.status.neutralBorder,
        outline: {
          background: foundation.color.status.neutralSubtle,
          border: foundation.color.status.neutralBorder,
          text: foundation.color.status.neutral,
        },
        soft: {
          background: foundation.color.status.neutralSurface,
          text: foundation.color.status.neutral,
        },
        solid: {
          background: foundation.color.status.neutralStrong,
          text: foundation.color.text.inverse,
        },
        text: foundation.color.status.neutral,
      },
      success: {
        background: foundation.color.status.successSubtle,
        border: foundation.color.status.successBorder,
        outline: {
          background: foundation.color.status.successSubtle,
          border: foundation.color.status.successBorder,
          text: foundation.color.status.success,
        },
        soft: {
          background: foundation.color.status.successSurface,
          text: foundation.color.status.success,
        },
        solid: {
          background: foundation.color.status.success,
          text: foundation.color.text.inverse,
        },
        text: foundation.color.status.success,
      },
      warning: {
        background: foundation.color.status.warningSubtle,
        border: foundation.color.status.warningBorder,
        outline: {
          background: foundation.color.status.warningSubtle,
          border: foundation.color.status.warningBorder,
          text: foundation.color.status.warning,
        },
        soft: {
          background: foundation.color.status.warningSurface,
          text: foundation.color.status.warning,
        },
        solid: {
          background: foundation.color.status.warning,
          text: foundation.color.text.inverse,
        },
        text: foundation.color.status.warning,
      },
      danger: {
        background: foundation.color.status.dangerSubtle,
        border: foundation.color.status.dangerBorder,
        outline: {
          background: foundation.color.status.dangerSubtle,
          border: foundation.color.status.dangerBorder,
          text: foundation.color.status.danger,
        },
        soft: {
          background: foundation.color.status.dangerSurface,
          text: foundation.color.status.danger,
        },
        solid: {
          background: foundation.color.status.danger,
          text: foundation.color.text.inverse,
        },
        text: foundation.color.status.danger,
      },
      info: {
        background: foundation.color.status.infoSubtle,
        border: foundation.color.status.infoBorder,
        outline: {
          background: foundation.color.status.infoSubtle,
          border: foundation.color.status.infoBorder,
          text: foundation.color.status.info,
        },
        soft: {
          background: foundation.color.status.infoSurface,
          text: foundation.color.status.infoStrong,
        },
        solid: {
          background: foundation.color.status.info,
          text: foundation.color.text.inverse,
        },
        text: foundation.color.status.info,
      },
    },
    brandPanel: {
      backdropBlur: foundation.effect.blur.brandSurface,
      background: foundation.gradient.surface.brand,
      border: foundation.color.border.brandSurface,
      description: foundation.color.text.inverse,
      eyebrow: foundation.color.text.inverse,
      glow: foundation.effect.glow.brand,
      highlight: foundation.effect.highlight.brandSurface,
      media: {
        backdropBlur: foundation.effect.blur.brandMedia,
        background: foundation.color.surface.brandGlass,
        border: foundation.color.border.onBrand,
        highlight: foundation.effect.highlight.brand,
      },
      radius: foundation.shape.surface,
      text: foundation.color.text.onBrand,
    },
  },
} as const;

export type Tokens = typeof tokens;
