// Generated by scripts/generate-recent-updates.mjs. Do not edit manually.

export const latestUpdate = {
  date: "8 de setembro de 2026",
  title: "Entrega inicial do Clavia Design System",
} as const;

export const latestUpdates = [
  {
    date: "8 de setembro de 2026",
    title: "Entrega inicial do Clavia Design System",
  },
] as const;
